/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package calcapp;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        q2 classUnderTest = new q2();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
