/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cardapp;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        q1 classUnderTest = new q1();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
